name: mol_transformer
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - future=0.18.3
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - pip=23.0.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - pytz=2022.7
  - readline=8.2
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.65.0
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - appdirs==1.4.4
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.7
      - docker-pycreds==0.4.0
      - filelock==3.12.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - idna==3.4
      - jinja2==3.1.2
      - markupsafe==2.1.2
      - mpmath==1.3.0
      - networkx==3.1
      - pillow==9.5.0
      - protobuf==4.25.1
      - psutil==5.9.7
      - pyyaml==6.0.1
      - rdkit-pypi==2022.9.5
      - requests==2.29.0
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sympy==1.11.1
      - torch==2.0.0
      - torchtext==0.3.1
      - torchvision==0.15.1
      - typing-extensions==4.5.0
      - urllib3==1.26.15
      - wandb==0.16.1
