wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704629026.191397
    t:
      1:
      - 1
      - 40
      - 55
      2:
      - 1
      - 40
      - 55
      3:
      - 2
      - 23
      4: 3.11.3
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
