wandb_version: 1

experiment_group:
  desc: null
  value: x6mi2bwg
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704628977.126192
    t:
      1:
      - 1
      - 40
      - 55
      2:
      - 1
      - 40
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.3
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
